version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    groups:
      composer-dependencies:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: weekly
    groups:
      docs-dependencies:
        update-types:
          - minor
          - patch
